package lf.studio.api.domain.model.cliente;

public enum ServicosCliente {
    CORTE_SIMPLES,
    SOMBRANCELHA,
    ESCOVA,
    PROGRESSIVA,
    RECONSTRUCAO,
    HIDRATACAO,
    MASSAGEM_CAPILAR,
    APLIQUE_MEGA,
    MEGA_MANUTENCAO,
    DESCOLORACAO,
    ESCOVA_CHAPINHA,
    CORTE_FEMININO,
    UNHA_GEL,
    UNHA_PORCELANA,
    UNHA_ACRILICO,
    UNHA_FIBRAVIDRO,
    UNHA_POSTICA,
    MOLDE_F1,
    MANUTENCAO,
    SPA_PE,
    PE_MAO
}